// Single source of truth for the appointment_status enum (see
// supabase/migrations/20240101000001_enums.sql + 20240101000057_appointment_client_actions.sql
// for where each value was added at the database level).
//
// Two-track model — this is NOT one linear lifecycle, it's two different
// starting points that converge on the same terminal states:
//   - 1:1 appointments (client_id set, class_template_id null) are born
//     'pending_confirmation' and need an explicit confirm.
//   - Group class instances (generated by generate_class_instances) are
//     born 'scheduled' — capacity-gated, not confirmation-gated.
// Both paths converge on: confirmed → completed | no_show | cancelled.
// 'postpone_requested' is a client-initiated reschedule ask on a 1:1
// appointment, handled by an admin editing the date and saving.
export type AppointmentStatus =
  | 'pending_confirmation'
  | 'scheduled'
  | 'confirmed'
  | 'completed'
  | 'no_show'
  | 'cancelled'
  | 'postpone_requested';

export const APPOINTMENT_STATUSES: readonly AppointmentStatus[] = [
  'pending_confirmation',
  'scheduled',
  'confirmed',
  'completed',
  'no_show',
  'cancelled',
  'postpone_requested',
];

// A status the client/coach/admin still needs to act on or attend —
// used by every "upcoming appointments" list across both apps.
export function isActiveAppointmentStatus(status: AppointmentStatus): boolean {
  return status === 'pending_confirmation' || status === 'scheduled'
    || status === 'confirmed' || status === 'postpone_requested';
}

export interface AppointmentOccurrence {
  start_time: string;
  end_time: string;
}

// Generates the N weekly occurrences of a recurring 1:1 appointment
// (including the first one, at startISO/endISO unchanged) — plain instant
// arithmetic, not calendar-aware, matching how the rest of this schema
// already treats appointment times as absolute TIMESTAMPTZ instants.
export function computeWeeklyOccurrences(
  startISO: string,
  endISO: string,
  occurrences: number,
): AppointmentOccurrence[] {
  const count = Math.max(1, Math.floor(occurrences));
  const start = new Date(startISO).getTime();
  const end = new Date(endISO).getTime();
  const WEEK_MS = 7 * 24 * 60 * 60 * 1000;

  return Array.from({ length: count }, (_, i) => ({
    start_time: new Date(start + i * WEEK_MS).toISOString(),
    end_time: new Date(end + i * WEEK_MS).toISOString(),
  }));
}
