-- ============================================================
-- Migration 000145: Document why avatars stay publicly readable
--
-- The audit flagged avatars_public_read (000105) as inconsistent with
-- videos/video-thumbnails, which were tightened to authenticated +
-- tenant-folder reads in 000110 after they turned out to gate paid
-- content. Reviewed and left as-is on purpose, not an oversight:
--
--   1. Low sensitivity — profile photos, not paid/paywalled content.
--   2. The check-in monitor kiosk (apps/web/src/app/monitor/[branchId])
--      has NO user session at all (it's a public unattended screen at
--      the gym entrance) and renders a scanning client's avatar_url
--      directly via a plain <img src> the instant they check in — see
--      monitor-display.tsx:296. Restricting this bucket to
--      `authenticated` (the videos pattern) would 403 every avatar on
--      that screen and break an already-shipped feature.
--
-- Write access was already correctly scoped to each user's own folder
-- (avatars_user_insert/update/delete, unchanged here) — only read
-- was ever public, and that's staying public deliberately.
-- ============================================================

-- No SQL to run: storage.objects is owned by Supabase's internal storage
-- role, so even COMMENT ON POLICY is rejected for the migration role on a
-- hosted project (SQLSTATE 42501, "must be owner of relation objects").
-- This file exists purely so the decision above is recorded in git history
-- next to the 000105/000110 migrations it references, not as a live schema
-- change.
SELECT 1;
